# Generated by Django 6.0 on 2025-12-05 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('info', models.TextField()),
                ('dates', models.DateTimeField()),
                ('location', models.CharField(max_length=220)),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Published'), ('c', 'canceled')], default='d', max_length=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Event', to='events.category')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organizer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
